# A service account needs to be defined and applied to your workload.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mapstore-sa

---
# A role with the proper ConfigMap permission needs to be created.
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mapstore-role
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "create", "update", "delete"]
    # Optionally uncomment the next line to limit the scope of the role by ConfigMap name(s).
    # resourceNames: ["my-mapstore-config-map-name", "list-all-map-names-one-at-a-time"]

---
# The above role needs to be bound to the above service account.
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mapstore-role-binding
roleRef:
  kind: Role
  name: mapstore-role # Must match above Role name.
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: mapstore-sa # Must match above ServiceAccount name.
    namespace: default # Change to match your namespace.

---
# The service account above needs to be applied to your workload (using a deployment as an example).
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mapstore-example
  namespace: default # Change to match your namespace.
spec:
  selector:
    matchLabels:
      app: mapstore-example
  template:
    metadata:
      labels:
        app: mapstore-example
    spec:
      serviceAccountName: mapstore-sa # Must match above ServiceAccount name.
      containers:
        - name: define-container-below
